### ISSUE TITLE
Pickling the encoder fails

### ISSUE THREAD

**Issue by schumajs** [DwangoMediaVillage/pqkmeans#12]
Hi guys,

first of all thanks for the lib. I'm currently trying it out but having a hard time persisting the encoder:

The following snippet

```python
    encoder = pqkmeans.encoder.PQEncoder(num_subdim=4, Ks=256)
    
    encoder.fit(features)

    with open('/Users/schumajs/Desktop/encoder.pkl', 'wb') as f:
        pickle.dump(encoder, f)
```

returns

```
pickle.PicklingError: Can't pickle <class 'pqkmeans.encoder.pq_encoder.TrainedPQEncoder'>: it's not found as pqkmeans.encoder.pq_encoder.TrainedPQEncoder
```

Any ideas?

Thank you

Jens

**EDIT**

Saving the encoder works with python 3. I have been using python 2. Sorry for that.

On a different matter: Would it be possible to save the trained pqkmeans model as well?

**Comment by matsui528** [comment]
Hi @schumajs,

The problem was that a nested class cannot be pickled in Python2. I solved this in #13.

Curretnly, the trained pqkmeans model (k-means-instance created by PQKMeans(encoder=encoder, k=K)) cannot be directly saved. Please write/read the encoder and call PQKMeans when you run clustering.

**Comment by matsui528** [comment]
oh, I might misunderstand. The trained pqkmeans model means that cluster_centers after the clustering is finished? Yes, that should be saved. I'll work on it

**Comment by schumajs** [comment]
Exactly, ideally I want to train the encoder and the kmeans once, save it and use it for vector quantization later. Thank you for your efforts!

**Comment by insikk** [comment]
@schumajs Good new for you. Now you can save and load kmeans clustering result. 
* Saving kmeans clustering: save the found centers
* Loading: initialize pqkmeans clustering with the saved initial centers, and execute predict function.

Please refer this code 
https://github.com/DwangoMediaVillage/pqkmeans/blob/master/test/clustering/test_pqkmeans.py#L55

**Comment by schumajs** [comment]
Sorry for the late Answer. Thank you!
