### ISSUE TITLE
init PQkmeans class with cluster centers

### ISSUE THREAD

**Issue by insikk** [DwangoMediaVillage/pqkmeans#16]
This awesome repo saves me a lot of time that could be wasted otherwise if I was stick to Ak-means clustering. Still it requires long time to fit PQkmeans object. I want to save its result, which is the found cluster centers. Then I want to use the saved result for assigning any descriptor to the most nearest center point. 

First, I tried with pickle, but PQkmeans object cannot be pickled. 

Seconds, I tried to saving only found cluster centers in `.npy` format. However, there is no way to initialize PQkmeans object with initial center points. The reason why I want to create PQkmeans clustering is that I want to use efficient assignment step.

My suggestion is 
* Create option to initialize PQkmeans object with initial center points, so user can predict with the object. 
* Provide static method which is used for assignment step, so user can assign most nearest cluster center for batch of descriptors. 

Do you have any plan to implement this feature? This will make this work more usable and complete.

**Comment by insikk** [comment]
I am working on extending current pqkmeans constructor. So it can take initial centers. 
https://github.com/insikk/pqkmeans/tree/constructor

I'll send PR after finishing my task.

**Comment by matsui528** [comment]
Hi @insikk 
Make sense. Waiting for your PR!

**Comment by insikk** [comment]
@matsui528 
Here is the PR. https://github.com/DwangoMediaVillage/pqkmeans/pull/17
