### ISSUE TITLE
Comparision to Faiss 

### ISSUE THREAD

**Issue by insikk** [DwangoMediaVillage/pqkmeans#19]
[Faiss](https://github.com/facebookresearch/faiss) implemented k-means clustering in PQ space. 

According to https://github.com/facebookresearch/faiss/wiki/Low-level-benchmarks, it shows very competitive result on million scale thanks to GPU acceleration.

However,  there is lack of billion scale benchmark data so I cannot compare which one is faster. 

In [Billion-scale similarity search with GPUs](https://arxiv.org/pdf/1702.08734.pdf) by Jeff Johnson, Matthijs Douze, Hervé Jégou

I have two glimpses that Faiss may faster than PQk-menas.

## 1. Million scale test
> **Large scale.** We can also compare to [3], an approximate CPU method that clusters 100M 128-d vectors to 85k centroids. Their clustering method runs in 46 minutes, but requires 56 minutes (at least) of pre-processing to encode the vectors. Our method performs exact k-means on 4 GPUs in 52 minutes without any pre-processing.

The quote says, N=100M, 128D (SIFT dim), K=10^5 (approx) took about 1h (except pq encoding part). 
(iteration unknown)
Your paper Table 5. shows SIFT 1B (128D). N=1M, K=10^5 took 14h for 5 iter. 
![image](https://user-images.githubusercontent.com/2110359/35180248-f605ae06-fdef-11e7-9586-c1235ef70bca.png)

If I naively multiply 10 to the Faiss result because N is 10x smaller for the benchmark, it took 10h. 

## 2. 1-nearest-neighbor. Assignment Step Speed

Another point is comparing assignment step in your paper Table3. SIFT1M K = 10^3. Assignment step took 6 sec. 
![image](https://user-images.githubusercontent.com/2110359/35180246-e6ed183c-fdef-11e7-87d8-a66e8112bcd0.png)

Below figure from Faiss tells it took less than 1 sec.
![image](https://user-images.githubusercontent.com/2110359/35180226-2173c06a-fdef-11e7-98d1-73d4c04738b6.png)

## Questions

Do you have any data for rigorous comparison? Your PQk-means and Faiss implementation is both competitive. I want to see who wins in terms of speed and accuracy performance. 

One more question. Suppose your proposed update step can be mixed with faiss implementation, will it produce the state-of-the-art PQk-means clustering implementation?

**Comment by matsui528** [comment]
Hi @insikk 

First of all, the k-means of faiss is a fast implementation of the ``exact'' k-means (inputs are D-dim vectors). It is run on the D-dim feature space, not on the PQ-space. So the k-means of faiss and PQ-kmeans, which is run on the PQ-space, are different methods.

Yes, we'd like to compare PQk-means with the k-means implementation of faiss. We plan to upload a tutorial of the comparison.

Combining faiss and PQk-means is one option. But we're more interested in the direct GPU implementation of PQk-means.

Btw if you're interested in GPU, please feel free to PR about it :)  We don't have enough time to implement that. We're planning:
- As a reference, implement the pure Python PQk-means with numpy (current impl is c++)
- Check the accuracy of Pure Python impl is the same as that of c++ (computational cost would be slower)
- Replace numpy to [cupy](https://cupy.chainer.org/), which is the easiest way to create a GPU implementation without any special dependencies

**Comment by matsui528** [comment]
Hi @insikk,

I compared PQk-means to Faiss. See the tutorial 4: https://github.com/DwangoMediaVillage/pqkmeans/blob/master/tutorial/4_comparison_to_faiss.ipynb
