### ISSUE TITLE
How to speed up the "predict" function?

### ISSUE THREAD

**Issue by jonbakerfish** [DwangoMediaVillage/pqkmeans#24]
After training the PQ-kmeans (with num_subdim=16, Ks = 256, kmeans.K = 25,000), I want to assign ~1,000,000 vectors to their clusters, but the `kmeans.predict(new_vectors)` takes a long time to run. Why this is slow and is there any method to speed up?

**Comment by matsui528** [comment]
Hi @jonbakerfish 
Thanks for pointing it out. I found that the `predict` function is not parallelized. I'll make it faster

**Comment by kogaki** [comment]
#25 must fixed this issue. Thank you for your report.
