### ISSUE TITLE
create pqkmeans conda package version from pypi

### ISSUE THREAD

**Issue by arngolo** [DwangoMediaVillage/pqkmeans#35]
I am failing to create a conda package of pqkmeans from pypi:

$conda skeleton pypi pqkmeans
$conda build pqkmeans

it ends with error exit (1)!!!!
Don't know how to solve the problem. sorry for my ignorance!!!

I really need pqkmeans from conda environment!
Is there any known anaconda channel from where I can conda install pqkmeans?

**Comment by Hi-king** [comment]
@arngolo Thank you for trying our package!

Although it's best to produce anaconda packages available for every environments, it takes a little bit cost to build in those environments.

So, the fastest solution is build your own package on your environment.
Following are the steps I successfully built my conda package


1.  build dependecy packages

```
conda skeleton pypi pipe
conda build pipe
conda skeleton pypi texmex_python
conda build texmex_python
conda skeleton pypi lshash3 # because there are no osx-64 build
conda build lshash3
```

2. create pqkmeans installation config

I found there needs few modifications from automatically created `meta.yml`

```
conda skeleton pypi pqkmeans
emacs pqkmeans/meta.yaml # with your preferred  editor
```
then change `test.imports` as follows.

```
test:
  imports:
    - pqkmeans
    - pqkmeans.clustering
    - pqkmeans.encoder
```

3. build and install

```
conda build pqkmeans
conda install --use-local pqkmeans
```
If you still cannot build, please tell me the error you've met :)

I'm sorry for there are no publicly available conda build of pqkmeans.

**Comment by arngolo** [comment]
> @arngolo Thank you for trying our package!
> 
> Although it's best to produce anaconda packages available for every environments, it takes a little bit cost to build in those environments.
> 
> So, the fastest solution is build your own package on your environment.
> Following are the steps I successfully built my conda package
> 
> 1. build dependecy packages
> 
> ```
> conda skeleton pypi pipe
> conda build pipe
> conda skeleton pypi texmex_python
> conda build texmex_python
> conda skeleton pypi lshash3 # because there are no osx-64 build
> conda build lshash3
> ```
> 
> 1. create pqkmeans installation config
> 
> I found there needs few modifications from automatically created `meta.yml`
> 
> ```
> conda skeleton pypi pqkmeans
> emacs pqkmeans/meta.yaml # with your preferred  editor
> ```
> 
> then change `test.imports` as follows because there are no use test-only imports (test, test.clustering, and so on)
> 
> ```
> test:
>   imports:
>     - pqkmeans
>     - pqkmeans.clustering
>     - pqkmeans.encoder
> ```
> 
> 1. build and install
> 
> ```
> conda build pqkmeans
> conda install --use-local pqkmeans
> ```
> 
> If you still cannot build, please tell me the error you've met :)
> 
> I'm sorry for there are no publicly available conda build of pqkmeans.

I am failing to build the Texmex_python and the lshash3 as well. Tried on mac and windows. python3.6 and 3.7

(conda_pqkmeans) C:\Users\arngo>conda skeleton pypi texmex_python
Using url https://files.pythonhosted.org/packages/05/e3/804a32f2e39f09f279063adc6098a29b523401f06a50a4c460ad1ff5c58a/texmex_python-1.0.0.tar.gz (2 KB) for texmex_python.
Downloading texmex_python
PyPI URL:  https://files.pythonhosted.org/packages/05/e3/804a32f2e39f09f279063adc6098a29b523401f06a50a4c460ad1ff5c58a/texmex_python-1.0.0.tar.gz
Using cached download
Unpacking texmex_python...
done
working in C:\Users\arngo\AppData\Local\Temp\tmp85eesa31conda_skeleton_texmex_python-1.0.0.tar.gz
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\arngo\miniconda3\conda-bld\skeleton_1591277008220\_h_env


The following NEW packages will be INSTALLED:

    ca-certificates: 2020.1.1-0
    certifi:         2020.4.5.1-py37_0
    openssl:         1.1.1g-he774522_0
    pip:             20.0.2-py37_3
    python:          3.7.7-h81c818b_4
    pyyaml:          5.3.1-py37he774522_0
    setuptools:      46.4.0-py37_0
    sqlite:          3.31.1-h2a8f88b_1
    vc:              14.1-h0510ff6_4
    vs2015_runtime:  14.16.27012-hf0eaf9b_2
    wheel:           0.34.2-py37_0
    wincertstore:    0.2-py37_0
    yaml:            0.1.7-hc54c509_2
    zlib:            1.2.11-h62dcd97_4

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Applying patch: 'C:\\Users\\arngo\\AppData\\Local\\Temp\\tmp85eesa31conda_skeleton_texmex_python-1.0.0.tar.gz\\pypi-distutils.patch'
Trying to apply patch as-is
INFO:conda_build.source:Trying to apply patch as-is
INFO conda_build.source:apply_patch(596): Trying to apply patch as-is
(Stripping trailing CRs from patch; use --binary to disable.)
patching file core.py
Hunk #1 succeeded at 167 with fuzz 2 (offset 1 line).
Writing recipe for texmex_python
--dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.

INFO:conda_build.config:--dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.

INFO conda_build.config:__exit__(800): --dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.


(conda_pqkmeans) C:\Users\arngo>conda build texmex_python
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for texmex_python
INFO:conda_build.metadata:Attempting to finalize metadata for texmex_python
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
INFO conda_build.variants:_combine_spec_dictionaries(188): Adding in variants from config.variant
Missing dependency lshash3, but found recipe directory, so building lshash3 first
Attempting to finalize metadata for lshash3
INFO:conda_build.metadata:Attempting to finalize metadata for lshash3
INFO conda_build.metadata:finalize_outputs_pass(700): Attempting to finalize metadata for lshash3
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['lshash3-0.0.8-py37_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\_h_env


The following NEW packages will be INSTALLED:

    ca-certificates: 2020.1.1-0
    certifi:         2020.4.5.1-py37_0
    openssl:         1.1.1g-he774522_0
    pip:             20.0.2-py37_3
    python:          3.7.7-h81c818b_4
    setuptools:      46.4.0-py37_0
    sqlite:          3.31.1-h2a8f88b_1
    vc:              14.1-h0510ff6_4
    vs2015_runtime:  14.16.27012-hf0eaf9b_2
    wheel:           0.34.2-py37_0
    wincertstore:    0.2-py37_0
    zlib:            1.2.11-h62dcd97_4

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Source cache directory is: C:\Users\arngo\miniconda3\conda-bld\src_cache
INFO:conda_build.source:Source cache directory is: C:\Users\arngo\miniconda3\conda-bld\src_cache
INFO conda_build.source:download_to_cache(43): Source cache directory is: C:\Users\arngo\miniconda3\conda-bld\src_cache
Found source in cache: lshash3-0.0.8_aec1836231.tar.gz
INFO:conda_build.source:Found source in cache: lshash3-0.0.8_aec1836231.tar.gz
INFO conda_build.source:download_to_cache(63): Found source in cache: lshash3-0.0.8_aec1836231.tar.gz
Extracting download
source tree in: C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\work
Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0. If this recipe does not use a compiler, this message is safe to ignore.  Otherwise, use {{compiler('<language>')}} jinja2 in requirements/build.
WARNING:conda_build.windows:Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0. If this recipe does not use a compiler, this message is safe to ignore.  Otherwise, use {{compiler('<language>')}} jinja2 in requirements/build.
WARNING conda_build.windows:msvc_env_cmd(91): Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0. If this recipe does not use a compiler, this message is safe to ignore.  Otherwise, use {{compiler('<language>')}} jinja2 in requirements/build.
Rewriting env in output: {'BUILD_PREFIX': 'C:\\Users\\arngo\\miniconda3\\conda-bld\\lshash3_1591277050672\\_build_env',
 'PREFIX': 'C:\\Users\\arngo\\miniconda3\\conda-bld\\lshash3_1591277050672\\_h_env',
 'SRC_DIR': 'C:\\Users\\arngo\\miniconda3\\conda-bld\\lshash3_1591277050672\\work'}

(conda_pqkmeans) %SRC_DIR%>IF "" == "" (call %SRC_DIR%\build_env_setup.bat )

(conda_pqkmeans) %SRC_DIR%>set "CONDA_BUILD=1"

(conda_pqkmeans) %SRC_DIR%>set "PYTHONNOUSERSITE=1"

(conda_pqkmeans) %SRC_DIR%>set "CONDA_DEFAULT_ENV=%PREFIX%"

(conda_pqkmeans) %SRC_DIR%>set "ARCH=64"

(conda_pqkmeans) %SRC_DIR%>set "PREFIX=%PREFIX%"

(conda_pqkmeans) %SRC_DIR%>set "BUILD_PREFIX=%BUILD_PREFIX%"

(conda_pqkmeans) %SRC_DIR%>set "SYS_PREFIX=C:\Users\arngo\miniconda3"

(conda_pqkmeans) %SRC_DIR%>set "SYS_PYTHON=C:\Users\arngo\miniconda3\python.exe"

(conda_pqkmeans) %SRC_DIR%>set "SUBDIR=win-64"

(conda_pqkmeans) %SRC_DIR%>set "SRC_DIR=%SRC_DIR%"

(conda_pqkmeans) %SRC_DIR%>set "ROOT=C:\Users\arngo\miniconda3"

(conda_pqkmeans) %SRC_DIR%>set "CONDA_PY=37"

(conda_pqkmeans) %SRC_DIR%>set "PY3K=1"

(conda_pqkmeans) %SRC_DIR%>set "PY_VER=3.7"

(conda_pqkmeans) %SRC_DIR%>set "STDLIB_DIR=%PREFIX%\Lib"

(conda_pqkmeans) %SRC_DIR%>set "SP_DIR=%PREFIX%\Lib\site-packages"

(conda_pqkmeans) %SRC_DIR%>set "PYTHON=%PREFIX%\python.exe"

(conda_pqkmeans) %SRC_DIR%>set "NPY_VER=1.11"

(conda_pqkmeans) %SRC_DIR%>set "CONDA_NPY=1.11"

(conda_pqkmeans) %SRC_DIR%>set "NPY_DISTUTILS_APPEND_FLAGS=1"

(conda_pqkmeans) %SRC_DIR%>set "PERL_VER=5.26"

(conda_pqkmeans) %SRC_DIR%>set "CONDA_PERL=5.26.0"

(conda_pqkmeans) %SRC_DIR%>set "LUA_VER=5"

(conda_pqkmeans) %SRC_DIR%>set "CONDA_LUA=5"

(conda_pqkmeans) %SRC_DIR%>set "R_VER=3.4"

(conda_pqkmeans) %SRC_DIR%>set "CONDA_R=3.4"

(conda_pqkmeans) %SRC_DIR%>set "PKG_NAME=lshash3"

(conda_pqkmeans) %SRC_DIR%>set "PKG_VERSION=0.0.8"

(conda_pqkmeans) %SRC_DIR%>set "PKG_BUILDNUM=0"

(conda_pqkmeans) %SRC_DIR%>set "PKG_BUILD_STRING=placeholder"

(conda_pqkmeans) %SRC_DIR%>set "PKG_HASH=1234567"

(conda_pqkmeans) %SRC_DIR%>set "RECIPE_DIR=C:\Users\arngo\lshash3"

(conda_pqkmeans) %SRC_DIR%>set "CPU_COUNT=4"

(conda_pqkmeans) %SRC_DIR%>set "SHLIB_EXT=.dll"

(conda_pqkmeans) %SRC_DIR%>set "PATH=%BUILD_PREFIX%;%BUILD_PREFIX%\Library\mingw-w64\bin;%BUILD_PREFIX%\Library\usr\bin;;%BUILD_PREFIX%\Library\bin;%BUILD_PREFIX%\Scripts;%BUILD_PREFIX%\Scripts;%PREFIX%;%PREFIX%\Library\mingw-w64\bin;%PREFIX%\Library\usr\bin;;%PREFIX%\Library\bin;%PREFIX%\Scripts;%PREFIX%\Scripts;C:\Users\arngo\miniconda3;C:\Users\arngo\miniconda3\Library\mingw-w64\bin;C:\Users\arngo\miniconda3\Library\usr\bin;C:\Users\arngo\miniconda3\Library\bin;C:\Users\arngo\miniconda3\Scripts;C:\Users\arngo\miniconda3\bin;C:\Users\arngo\miniconda3\envs\conda_pqkmeans;C:\Users\arngo\miniconda3\envs\conda_pqkmeans\Library\mingw-w64\bin;C:\Users\arngo\miniconda3\envs\conda_pqkmeans\Library\usr\bin;C:\Users\arngo\miniconda3\envs\conda_pqkmeans\Library\bin;C:\Users\arngo\miniconda3\envs\conda_pqkmeans\Scripts;C:\Users\arngo\miniconda3\envs\conda_pqkmeans\bin;"C:\Python36\Scripts"\C:\Users\arngo\miniconda3;C:\Users\arngo\miniconda3\Library\mingw-w64\bin;C:\Users\arngo\miniconda3\Library\usr\bin;C:\Users\arngo\miniconda3\Library\bin;C:\Users\arngo\miniconda3\Scripts;C:\Users\arngo\miniconda3\bin;C:\Users\arngo\miniconda3\condabin;C:\Python36\Scripts;C:\Python36;C:\Python37\Scripts;C:\Python37;C:\Scripts;C:\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\Google protobuf\bin;C:\Users\arngo\AppData\Local\Microsoft\WindowsApps;.;C:\Program Files\snap\bin"

(conda_pqkmeans) %SRC_DIR%>set "SCRIPTS=%PREFIX%\Scripts"

(conda_pqkmeans) %SRC_DIR%>set "LIBRARY_PREFIX=%PREFIX%\Library"

(conda_pqkmeans) %SRC_DIR%>set "LIBRARY_BIN=%PREFIX%\Library\bin"

(conda_pqkmeans) %SRC_DIR%>set "LIBRARY_INC=%PREFIX%\Library\include"

(conda_pqkmeans) %SRC_DIR%>set "LIBRARY_LIB=%PREFIX%\Library\lib"

(conda_pqkmeans) %SRC_DIR%>set "CYGWIN_PREFIX=/cygdrive/c/Users/arngo/miniconda3/conda-bld/lshash3_1591277050672/_h_env"

(conda_pqkmeans) %SRC_DIR%>set "ALLUSERSPROFILE=C:\ProgramData"

(conda_pqkmeans) %SRC_DIR%>set "APPDATA=C:\Users\arngo\AppData\Roaming"

(conda_pqkmeans) %SRC_DIR%>set "CommonProgramFiles=C:\Program Files\Common Files"

(conda_pqkmeans) %SRC_DIR%>set "CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files"

(conda_pqkmeans) %SRC_DIR%>set "CommonProgramW6432=C:\Program Files\Common Files"

(conda_pqkmeans) %SRC_DIR%>set "COMPUTERNAME=ANGOLO2"

(conda_pqkmeans) %SRC_DIR%>set "ComSpec=C:\WINDOWS\system32\cmd.exe"

(conda_pqkmeans) %SRC_DIR%>set "HOMEDRIVE=C:"

(conda_pqkmeans) %SRC_DIR%>set "HOMEPATH=\Users\arngo"

(conda_pqkmeans) %SRC_DIR%>set "LOCALAPPDATA=C:\Users\arngo\AppData\Local"

(conda_pqkmeans) %SRC_DIR%>set "LOGONSERVER=\\ANGOLO2"

(conda_pqkmeans) %SRC_DIR%>set "NUMBER_OF_PROCESSORS=4"

(conda_pqkmeans) %SRC_DIR%>set "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW"

(conda_pqkmeans) %SRC_DIR%>set "ProgramData=C:\ProgramData"

(conda_pqkmeans) %SRC_DIR%>set "ProgramFiles=C:\Program Files"

(conda_pqkmeans) %SRC_DIR%>set "ProgramFiles(x86)=C:\Program Files (x86)"

(conda_pqkmeans) %SRC_DIR%>set "ProgramW6432=C:\Program Files"

(conda_pqkmeans) %SRC_DIR%>set "PROMPT=(conda_pqkmeans) $P$G"

(conda_pqkmeans) %SRC_DIR%>set "PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules"

(conda_pqkmeans) %SRC_DIR%>set "PUBLIC=C:\Users\Public"

(conda_pqkmeans) %SRC_DIR%>set "SystemDrive=C:"

(conda_pqkmeans) %SRC_DIR%>set "SystemRoot=C:\WINDOWS"

(conda_pqkmeans) %SRC_DIR%>set "TEMP=C:\Users\arngo\AppData\Local\Temp"

(conda_pqkmeans) %SRC_DIR%>set "TMP=C:\Users\arngo\AppData\Local\Temp"

(conda_pqkmeans) %SRC_DIR%>set "USERDOMAIN=ANGOLO2"

(conda_pqkmeans) %SRC_DIR%>set "USERNAME=arngo"

(conda_pqkmeans) %SRC_DIR%>set "USERPROFILE=C:\Users\arngo"

(conda_pqkmeans) %SRC_DIR%>set "windir=C:\WINDOWS"

(conda_pqkmeans) %SRC_DIR%>set "PROCESSOR_ARCHITECTURE=AMD64"

(conda_pqkmeans) %SRC_DIR%>set "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel"

(conda_pqkmeans) %SRC_DIR%>set "BUILD=amd64-pc-windows-19.0.0"

(conda_pqkmeans) %SRC_DIR%>set "r_base=3.4"

(conda_pqkmeans) %SRC_DIR%>set "cpu_optimization_target=nocona"

(conda_pqkmeans) %SRC_DIR%>set "cran_mirror=https://cran.r-project.org"

(conda_pqkmeans) %SRC_DIR%>set "target_platform=win-64"

(conda_pqkmeans) %SRC_DIR%>set "c_compiler=vs2017"

(conda_pqkmeans) %SRC_DIR%>set "cxx_compiler=vs2017"

(conda_pqkmeans) %SRC_DIR%>set "fortran_compiler=gfortran"

(conda_pqkmeans) %SRC_DIR%>set "vc=14"

(conda_pqkmeans) %SRC_DIR%>set "ignore_build_only_deps={'python', 'numpy'}"

(conda_pqkmeans) %SRC_DIR%>set "extend_keys={'extend_keys', 'ignore_version', 'pin_run_as_build', 'ignore_build_only_deps'}"

(conda_pqkmeans) %SRC_DIR%>set "pin_run_as_build=OrderedDict([('python', {'min_pin': 'x.x', 'max_pin': 'x.x'}), ('r-base', {'min_pin': 'x.x', 'max_pin': 'x.x'})])"

(conda_pqkmeans) %SRC_DIR%>set "CONDA_BUILD_STATE=BUILD"

(conda_pqkmeans) %SRC_DIR%>set "PIP_NO_BUILD_ISOLATION=False"

(conda_pqkmeans) %SRC_DIR%>set "PIP_NO_DEPENDENCIES=True"

(conda_pqkmeans) %SRC_DIR%>set "PIP_IGNORE_INSTALLED=True"

(conda_pqkmeans) %SRC_DIR%>set "PIP_CACHE_DIR=C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\pip_cache"

(conda_pqkmeans) %SRC_DIR%>set "PIP_NO_INDEX=True"

(conda_pqkmeans) %SRC_DIR%>set DISTUTILS_USE_SDK=1

(conda_pqkmeans) %SRC_DIR%>set MSSdk=1

(conda_pqkmeans) %SRC_DIR%>set PY_VCRUNTIME_REDIST=%PREFIX%\Library\bin\vcruntime140.dll

(conda_pqkmeans) %SRC_DIR%>set "VS_VERSION=14.0"

(conda_pqkmeans) %SRC_DIR%>set "VS_MAJOR=14"

(conda_pqkmeans) %SRC_DIR%>set "VS_YEAR=2015"

(conda_pqkmeans) %SRC_DIR%>set "CMAKE_GENERATOR=Visual Studio 14 2015 Win64"

(conda_pqkmeans) %SRC_DIR%>set "MSYS2_ARG_CONV_EXCL=/AI;/AL;/OUT;/out"

(conda_pqkmeans) %SRC_DIR%>set "MSYS2_ENV_CONV_EXCL=CL"

(conda_pqkmeans) %SRC_DIR%>call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
The system cannot find the path specified.

(conda_pqkmeans) %SRC_DIR%>set "INCLUDE=%PREFIX%\Library\include;"

(conda_pqkmeans) %SRC_DIR%>set "LIB=%PREFIX%\Library\lib;"

(conda_pqkmeans) %SRC_DIR%>call "C:\Users\arngo\miniconda3\Scripts\..\condabin\conda_hook.bat"

(conda_pqkmeans) %SRC_DIR%>call "C:\Users\arngo\miniconda3\Scripts\..\condabin\conda.bat" activate "%PREFIX%"

(%PREFIX%) %SRC_DIR%>call "C:\Users\arngo\miniconda3\Scripts\..\condabin\conda.bat" activate --stack "%BUILD_PREFIX%"
Not a conda environment: C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\_build_env

(%PREFIX%) %SRC_DIR%>REM ===== end generated header =====

(%PREFIX%) %SRC_DIR%>%PREFIX%\python.exe -m pip install . -vv
Non-user install because user site-packages disabled
Ignoring indexes: https://pypi.org/simple
Created temporary directory: C:\Users\arngo\AppData\Local\Temp\pip-ephem-wheel-cache-vzvscyli
Created temporary directory: C:\Users\arngo\AppData\Local\Temp\pip-req-tracker-cidiykic
Initialized build tracking at C:\Users\arngo\AppData\Local\Temp\pip-req-tracker-cidiykic
Created build tracker: C:\Users\arngo\AppData\Local\Temp\pip-req-tracker-cidiykic
Entered build tracker: C:\Users\arngo\AppData\Local\Temp\pip-req-tracker-cidiykic
Created temporary directory: C:\Users\arngo\AppData\Local\Temp\pip-install-s1lqbvgc
Processing c:\users\arngo\miniconda3\conda-bld\lshash3_1591277050672\work
  Created temporary directory: C:\Users\arngo\AppData\Local\Temp\pip-req-build-tw5zqjnb
  Added file:///C:/Users/arngo/miniconda3/conda-bld/lshash3_1591277050672/work to build tracker 'C:\\Users\\arngo\\AppData\\Local\\Temp\\pip-req-tracker-cidiykic'
    Running setup.py (path:C:\Users\arngo\AppData\Local\Temp\pip-req-build-tw5zqjnb\setup.py) egg_info for package from file:///C:/Users/arngo/miniconda3/conda-bld/lshash3_1591277050672/work
    Running command python setup.py egg_info
    ERROR: Could not find a version that satisfies the requirement pyscaffold<2.6a0,>=2.5a0 (from versions: none)
    ERROR: No matching distribution found for pyscaffold<2.6a0,>=2.5a0
    Traceback (most recent call last):
      File "C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\_h_env\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\_h_env\lib\subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Users\\arngo\\miniconda3\\conda-bld\\lshash3_1591277050672\\_h_env\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\arngo\\AppData\\Local\\Temp\\tmph68rw7oq', '--quiet', 'pyscaffold<2.6a0,>=2.5a0']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\arngo\AppData\Local\Temp\pip-req-build-tw5zqjnb\setup.py", line 19, in <module>
        setup_package()
      File "C:\Users\arngo\AppData\Local\Temp\pip-req-build-tw5zqjnb\setup.py", line 15, in setup_package
        use_pyscaffold=True)
      File "C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\_h_env\lib\site-packages\setuptools\__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\_h_env\lib\site-packages\setuptools\__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\_h_env\lib\site-packages\setuptools\dist.py", line 698, in fetch_build_eggs
        replace_conflicting=True,
      File "C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\_h_env\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
        replace_conflicting=replace_conflicting
      File "C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\_h_env\lib\site-packages\pkg_resources\__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\_h_env\lib\site-packages\pkg_resources\__init__.py", line 1078, in obtain
        return installer(requirement)
      File "C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\_h_env\lib\site-packages\setuptools\dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "C:\Users\arngo\miniconda3\conda-bld\lshash3_1591277050672\_h_env\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['C:\\Users\\arngo\\miniconda3\\conda-bld\\lshash3_1591277050672\\_h_env\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\arngo\\AppData\\Local\\Temp\\tmph68rw7oq', '--quiet', 'pyscaffold<2.6a0,>=2.5a0']' returned non-zero exit status 1.
Cleaning up...
  Removing source in C:\Users\arngo\AppData\Local\Temp\pip-req-build-tw5zqjnb
Removed file:///C:/Users/arngo/miniconda3/conda-bld/lshash3_1591277050672/work from build tracker 'C:\\Users\\arngo\\AppData\\Local\\Temp\\pip-req-tracker-cidiykic'
Removed build tracker: 'C:\\Users\\arngo\\AppData\\Local\\Temp\\pip-req-tracker-cidiykic'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "%PREFIX%\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "%PREFIX%\lib\site-packages\pip\_internal\commands\install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "%PREFIX%\lib\site-packages\pip\_internal\legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "%PREFIX%\lib\site-packages\pip\_internal\legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "%PREFIX%\lib\site-packages\pip\_internal\legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "%PREFIX%\lib\site-packages\pip\_internal\operations\prepare.py", line 516, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "%PREFIX%\lib\site-packages\pip\_internal\operations\prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "%PREFIX%\lib\site-packages\pip\_internal\distributions\sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "%PREFIX%\lib\site-packages\pip\_internal\req\req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "%PREFIX%\lib\site-packages\pip\_internal\req\req_install.py", line 544, in _generate_metadata
    details=self.name or "from {}".format(self.link)
  File "%PREFIX%\lib\site-packages\pip\_internal\operations\build\metadata_legacy.py", line 118, in generate_metadata
    command_desc='python setup.py egg_info',
  File "%PREFIX%\lib\site-packages\pip\_internal\utils\subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Traceback (most recent call last):
  File "C:\Users\arngo\miniconda3\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\arngo\miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "C:\Users\arngo\miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "C:\Users\arngo\miniconda3\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Users\arngo\miniconda3\lib\site-packages\conda_build\build.py", line 2344, in build_tree
    notest=notest,
  File "C:\Users\arngo\miniconda3\lib\site-packages\conda_build\build.py", line 1459, in build
    windows.build(m, build_file, stats=build_stats, provision_only=provision_only)
  File "C:\Users\arngo\miniconda3\lib\site-packages\conda_build\windows.py", line 294, in build
    check_call_env(cmd, cwd=m.config.work_dir, stats=stats, rewrite_stdout_env=rewrite_env)
  File "C:\Users\arngo\miniconda3\lib\site-packages\conda_build\utils.py", line 398, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "C:\Users\arngo\miniconda3\lib\site-packages\conda_build\utils.py", line 378, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.
