### ISSUE TITLE
Get Subvector to run with other algorithment

### ISSUE THREAD

**Issue by Chuvantinh** [DwangoMediaVillage/pqkmeans#37]
HI Author,
I'm using now PQKmeans to compress the high dimension to the lower dimension with product quantization.
But my professor told me that I have to try a dataset with many algorithms after the processing product quantization. Because he wants to try with each sub-vector.
That means, After "Encode.transform() " function I have to get the subvector.
E.g: 10000 element , in 100 dimension ----> after product quantization -> = 5 x 10000 in 20 dimension (number divide is 5).
Then I would like to get the separated sub-vector. 
I have had a search on your package and google but I did not find the solution for that.
I would ask you : 
Is that possible to get sub-vector on product quantization?

thank you very much

**Comment by matsui528** [comment]
See this. You can reconstruct the original vector by `encoder.inverse_transform(pqcode)`
https://github.com/DwangoMediaVillage/pqkmeans/blob/master/tutorial/1_pqkmeans.ipynb

**Comment by Chuvantinh** [comment]
thank you.
At the beginning I have a vector 10000 X 100 Dimension: divide for 5 
After `encoder.transform`, I take the new vector id via Product quantization: that I take only a new vector : (20000, 5)
But I think After the processing `encoder.inverse_transform(pqcode)`  I take a new vector (20000, 100). 
I thought I had better take 5 Vector **(20000, 100)** in order to run with other algorithms ?

did I mean exactly ? pls help me  thanks

**Comment by matsui528** [comment]
No.
- After running PQ with M=5, the result would be five integers per vector, i.e., shape=(10000, 5) with dtype=uint8.
- `inverse_transform` reconstructs the original vector, i.e., shape=(10000, 100) with dtype=float64

```python
import numpy as np
import pqkmeans

X = np.random.random((10000, 100))
print(X.shape, X.dtype)  # (10000, 100) float64

encoder = pqkmeans.encoder.PQEncoder(num_subdim=5, Ks=256)
encoder.fit(X)

X_pqcode = encoder.transform(X)
print(X_pqcode.shape, X_pqcode.dtype)  # (10000, 5) uint8

X_reconstructed = encoder.inverse_transform(X_pqcode)
print(X_reconstructed.shape, X_reconstructed.dtype)  # (10000, 100) float64
```

See the original paper for the detail of the algorithm
https://lear.inrialpes.fr/pubs/2011/JDS11/jegou_searching_with_quantization.pdf
