### ISSUE TITLE
Sparse Vector

### ISSUE THREAD

**Issue by arita37** [DwangoMediaVillage/pqkmeans#44]
Just wondering,
if pqkmeans can be optimized for sparse vectors 
, csr format, instead of dense ones

thank you

**Comment by matsui528** [comment]
No. You need to convert sparse vectors to dense ones before applying pqkmeans.

My general advice is to project the sparse data to a lower (denser) space, e.g., from D=10K to D=100. That way, PQ will work better.

**Comment by arita37** [comment]
Thanks.

Is there a way to project in a  fast way on
low dense ?
(umap exists but, not so fast).

Yes, kmeans require gaussian vectors…..

**Comment by matsui528** [comment]
You can try multiplying by a random matrix. Multiplication of a matrix and a sparse vector would be generally fast.

**Comment by arita37** [comment]
Thanks.

Interesting way to give “gaussianity” to
a vector…. and should preserve distance.
